classes:
- service.prometheus.server.container
- service.prometheus.alertmanager.container
- service.prometheus.pushgateway.container
parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'pushgateway'
              domain:
              - 'tasks.monitoring_pushgateway'
              type: A
              port: ${prometheus:pushgateway:bind:port}
            - name: 'prometheus'
              domain:
              - 'tasks.monitoring_server'
              type: A
              port: ${prometheus:server:bind:port}
            - name: 'alertmanager'
              domain:
              - 'tasks.monitoring_alertmanager'
              type: A
              port: ${prometheus:alertmanager:bind:port}
